fragment PerformerData on Performer {
  id
  name
  disambiguation
  urls
  gender
  birthdate
  ethnicity
  country
  eye_color
  height_cm
  measurements
  fake_tits
  penis_length
  circumcised
  career_length
  tattoos
  piercings
  alias_list
  favorite
  ignore_auto_tag
  image_path
  scene_count
  image_count
  gallery_count
  group_count
  performer_count
  o_counter
  sex_scene_count
  oral_scene_count
  solo_scene_count
  facial_scene_count
  sex_giver_count
  sex_receiver_count
  oral_giver_count
  oral_receiver_count
  facial_giver_count
  facial_receiver_count

  tags {
    ...SlimTagData
  }

  stash_ids {
    stash_id
    endpoint
    updated_at
  }
  rating100
  details
  death_date
  hair_color
  weight

  custom_fields
}
