fragment PerformerData on Performer {
  id
  name
  disambiguation
  urls
  gender
  birthdate
  ethnicity
  country
  eye_color
  height_cm
  measurements
  fake_tits
  penis_length
  circumcised
  career_length
  tattoos
  piercings
  alias_list
  favorite
  ignore_auto_tag
  image_path
  scene_count
  image_count
  gallery_count
  group_count
  performer_count
  o_counter
  sex_scene_count
  oral_scene_count
  solo_scene_count
  facial_scene_count
  sex_top_count
  sex_bottom_count
  oral_top_count
  oral_bottom_count
  facial_top_count
  facial_bottom_count
  facial_marker_count
  facial_marker_top_count
  facial_marker_bottom_count
  facial_marker_with_top_count
  facial_marker_with_bottom_count
  orgasm_top_count
  feet_top_count
  feet_marker_count
  sex_with_top_count
  sex_with_bottom_count
  oral_with_top_count
  oral_with_bottom_count
  facial_with_top_count
  facial_with_bottom_count
  sex_unique_partner_count
  oral_unique_partner_count
  facial_unique_partner_count

  tags {
    ...SlimTagData
  }

  stash_ids {
    stash_id
    endpoint
    updated_at
  }
  rating100
  details
  death_date
  hair_color
  weight

  custom_fields

  additional_images {
    id
    performer_id
    image_path
    position
  }
}

mutation PerformerImageUpload($performer_id: ID!, $image: String!) {
  performerImageUpload(performer_id: $performer_id, image: $image) {
    id
    performer_id
    image_path
    position
  }
}

mutation PerformerImageDelete($id: ID!) {
  performerImageDelete(id: $id)
}

mutation PerformerImageSetDefault($id: ID!) {
  performerImageSetDefault(id: $id) {
    id
    image_path
  }
}
