fragment SceneMarkerData on SceneMarker {
  id
  title
  seconds
  end_seconds
  stream
  preview
  screenshot

  scene {
    ...SceneMarkerSceneData
  }

  primary_tag {
    id
    name
    parents {
      id
    }
  }

  tags {
    id
    name
    parents {
      id
    }
  }

  performers {
    id
    name
    alias_list
    disambiguation
  }

  top_performers {
    id
    name
    alias_list
    disambiguation
    image_path
  }

  bottom_performers {
    id
    name
    alias_list
    disambiguation
    image_path
  }
}

fragment SceneMarkerSceneData on Scene {
  id
  title
  files {
    width
    height
    path
  }
  paths {
    stream
  }
  performers {
    id
    name
    image_path
  }
}
