fragment SceneData on Scene {
  id
  title
  code
  details
  director
  urls
  date
  effective_date
  rating100
  o_counter
  organized
  interactive
  interactive_speed
  captions {
    language_code
    caption_type
  }
  created_at
  updated_at
  resume_time
  last_played_at
  play_duration
  play_count

  play_history
  o_history

  files {
    ...VideoFileData
  }

  paths {
    screenshot
    preview
    stream
    webp
    vtt
    sprite
    funscript
    interactive_heatmap
    caption
  }

  scene_markers {
    ...SceneMarkerData
  }

  galleries {
    ...SlimGalleryData
  }

  direct_galleries {
    ...SlimGalleryData
  }

  studio {
    ...SlimStudioData
  }

  groups {
    group {
      ...GroupData
    }
    scene_index
  }

  tags {
    ...SlimTagData
  }

  performers {
    ...PerformerData
  }

  stash_ids {
    endpoint
    stash_id
    updated_at
  }

  sceneStreams {
    url
    mime_type
    label
  }

  custom_fields

  multi_segment_loop_presets {
    id
    scene_id
    name
    enabled
    current_segment_index
    segments {
      start
      end
    }
    created_at
    updated_at
  }

  negative_markers {
    id
    scene_id
    name
    start_seconds
    end_seconds
    created_at
    updated_at
  }

  releases {
    ...SceneReleaseData
  }
}

fragment SceneReleaseData on SceneRelease {
  id
  title
  code
  details
  director
  url
  date
  play_order
  created_at
  updated_at
  studio {
    ...SlimStudioData
  }
  paths {
    screenshot
  }
  files {
    ...VideoFileData
  }
  galleries {
    ...SlimGalleryData
  }
  streams {
    url
    mime_type
    label
  }
}

fragment SelectSceneData on Scene {
  id
  title
  date
  code
  studio {
    name
  }
  files {
    path
  }
  paths {
    screenshot
  }
}
