fragment StudioData on Studio {
  id
  name
  url
  urls
  parent_studio {
    id
    name
    url
    urls
    image_path
  }
  child_studios {
    id
    name
    image_path
  }
  ignore_auto_tag
  image_path
  scene_count
  scene_count_all: scene_count(depth: -1)
  sex_scene_count
  sex_scene_count_all: sex_scene_count(depth: -1)
  oral_scene_count
  oral_scene_count_all: oral_scene_count(depth: -1)
  solo_scene_count
  solo_scene_count_all: solo_scene_count(depth: -1)
  facial_scene_count
  facial_scene_count_all: facial_scene_count(depth: -1)
  unique_performer_count
  unique_performer_count_all: unique_performer_count(depth: -1)
  image_count
  image_count_all: image_count(depth: -1)
  gallery_count
  gallery_count_all: gallery_count(depth: -1)
  performer_count
  performer_count_all: performer_count(depth: -1)
  group_count
  group_count_all: group_count(depth: -1)
  stash_ids {
    stash_id
    endpoint
    updated_at
  }
  details
  rating100
  favorite
  aliases
  tags {
    ...SlimTagData
  }
  o_counter
}

fragment SelectStudioData on Studio {
  id
  name
  aliases
  details
  image_path

  parent_studio {
    id
    name
  }
}
