query FindPerformers(
  $filter: FindFilterType
  $performer_filter: PerformerFilterType
  $performer_ids: [Int!]
) {
  findPerformers(
    filter: $filter
    performer_filter: $performer_filter
    performer_ids: $performer_ids
  ) {
    count
    performers {
      ...PerformerData
    }
  }
}

query FindPerformer($id: ID!) {
  findPerformer(id: $id) {
    ...PerformerData
  }
}

query FindPerformersForSelect(
  $filter: FindFilterType
  $performer_filter: PerformerFilterType
  $ids: [ID!]
) {
  findPerformers(
    filter: $filter
    performer_filter: $performer_filter
    ids: $ids
  ) {
    count
    performers {
      ...SelectPerformerData
    }
  }
}

# CUSTOM: begin
query PerformerCoPerformersByRole($performer_id: ID!) {
  performerCoPerformersByRole(performer_id: $performer_id) {
    sex_as_top {
      performer {
        ...PerformerData
      }
      scene_count
    }
    sex_as_bottom {
      performer {
        ...PerformerData
      }
      scene_count
    }
    oral_as_top {
      performer {
        ...PerformerData
      }
      scene_count
    }
    oral_as_bottom {
      performer {
        ...PerformerData
      }
      scene_count
    }
    facial_as_top {
      performer {
        ...PerformerData
      }
      scene_count
    }
    facial_as_bottom {
      performer {
        ...PerformerData
      }
      scene_count
    }
    unique_count
  }
}

query PerformerCoPerformersMiniImages($performer_id: ID!) {
  performerCoPerformersByRole(performer_id: $performer_id) {
    sex_as_top { performer { id name image_path } scene_count }
    sex_as_bottom { performer { id name image_path } scene_count }
    oral_as_top { performer { id name image_path } scene_count }
    oral_as_bottom { performer { id name image_path } scene_count }
    facial_as_top { performer { id name image_path } scene_count }
    facial_as_bottom { performer { id name image_path } scene_count }
    unique_count
  }
}

query StudioPerformerCoPerformersMiniImages($performer_id: ID!, $studio_id: ID!, $depth: Int) {
  studioPerformerCoPerformersByRole(performer_id: $performer_id, studio_id: $studio_id, depth: $depth) {
    sex_as_top { performer { id name image_path } scene_count }
    sex_as_bottom { performer { id name image_path } scene_count }
    oral_as_top { performer { id name image_path } scene_count }
    oral_as_bottom { performer { id name image_path } scene_count }
    facial_as_top { performer { id name image_path } scene_count }
    facial_as_bottom { performer { id name image_path } scene_count }
    unique_count
  }
}
# CUSTOM: end
