query FindStudios($filter: FindFilterType, $studio_filter: StudioFilterType) {
  findStudios(filter: $filter, studio_filter: $studio_filter) {
    count
    studios {
      ...StudioData
    }
  }
}

query FindStudio($id: ID!) {
  findStudio(id: $id) {
    ...StudioData
  }
}

query FindStudioPerformerStats($id: ID!, $performerId: ID!) {
  findStudio(id: $id) {
    id
    scene_count(performer_id: $performerId)
    sex_scene_count(performer_id: $performerId)
    oral_scene_count(performer_id: $performerId)
    solo_scene_count(performer_id: $performerId)
    facial_scene_count(performer_id: $performerId)
    group_count(performer_id: $performerId)
    o_counter(performer_id: $performerId)
  }
}

query FindStudiosForSelect(
  $filter: FindFilterType
  $studio_filter: StudioFilterType
  $ids: [ID!]
) {
  findStudios(filter: $filter, studio_filter: $studio_filter, ids: $ids) {
    count
    studios {
      ...SelectStudioData
    }
  }
}
