// Code generated by hand for tests; mirrors github.com/stretchr/testify/mock patterns.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/stashapp/stash/pkg/models"
)

type RatingScoreReaderWriter struct {
	mock.Mock
}

func (_m *RatingScoreReaderWriter) SceneMode(ctx context.Context, sceneID int) (string, error) {
	ret := _m.Called(ctx, sceneID)
	return ret.String(0), ret.Error(1)
}

func (_m *RatingScoreReaderWriter) FindByEntity(ctx context.Context, entityType string, entityID int) ([]*models.RatingScore, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 []*models.RatingScore
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*models.RatingScore); ok {
		r0 = rf(ctx, entityType, entityID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*models.RatingScore)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *RatingScoreReaderWriter) Upsert(ctx context.Context, score *models.RatingScore) error {
	ret := _m.Called(ctx, score)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RatingScore) error); ok {
		r0 = rf(ctx, score)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *RatingScoreReaderWriter) Delete(ctx context.Context, entityType string, entityID int, section string, key string) (bool, error) {
	ret := _m.Called(ctx, entityType, entityID, section, key)
	return ret.Bool(0), ret.Error(1)
}

func (_m *RatingScoreReaderWriter) DeleteByEntity(ctx context.Context, entityType string, entityID int) error {
	ret := _m.Called(ctx, entityType, entityID)
	return ret.Error(0)
}

func (_m *RatingScoreReaderWriter) RecalculateRating(ctx context.Context, entityType string, entityID int) (int, error) {
	ret := _m.Called(ctx, entityType, entityID)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string, int) int); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		r0 = ret.Int(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *RatingScoreReaderWriter) ResetSceneScores(ctx context.Context, sceneID int) (bool, error) {
	ret := _m.Called(ctx, sceneID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, sceneID)
	} else {
		r0 = ret.Bool(0)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *RatingScoreReaderWriter) ResetAllSceneScores(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)
	return ret.Int(0), ret.Error(1)
}
