// Code generated by hand for tests; mirrors github.com/stretchr/testify/mock patterns.
package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/stashapp/stash/pkg/models"
)

// SceneLoopPresetReaderWriter is a mock for models.SceneLoopPresetReaderWriter.
type SceneLoopPresetReaderWriter struct {
	mock.Mock
}

func (_m *SceneLoopPresetReaderWriter) FindByScene(ctx context.Context, sceneID int) ([]*models.SceneLoopPreset, error) {
	ret := _m.Called(ctx, sceneID)

	var r0 []*models.SceneLoopPreset
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.SceneLoopPreset); ok {
		r0 = rf(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SceneLoopPreset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, sceneID)
	} else {
		r1, _ = ret.Error(1)
	}

	return r0, r1
}

func (_m *SceneLoopPresetReaderWriter) FindBySceneAndName(ctx context.Context, sceneID int, name string) (*models.SceneLoopPreset, error) {
	ret := _m.Called(ctx, sceneID, name)

	var r0 *models.SceneLoopPreset
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *models.SceneLoopPreset); ok {
		r0 = rf(ctx, sceneID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SceneLoopPreset)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, sceneID, name)
	} else {
		r1, _ = ret.Error(1)
	}

	return r0, r1
}

func (_m *SceneLoopPresetReaderWriter) Upsert(ctx context.Context, preset *models.SceneLoopPreset) error {
	ret := _m.Called(ctx, preset)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SceneLoopPreset) error); ok {
		r0 = rf(ctx, preset)
	} else {
		r0, _ = ret.Error(0)
	}

	return r0
}

func (_m *SceneLoopPresetReaderWriter) DeleteBySceneAndName(ctx context.Context, sceneID int, name string) error {
	ret := _m.Called(ctx, sceneID, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, sceneID, name)
	} else {
		r0, _ = ret.Error(0)
	}

	return r0
}
